version: '3.9'
services:
  homeassistant:
    container_name: homeassistant
    restart: unless-stopped
    privileged: true
    network_mode: "host"
    image: ghcr.nju.edu.cn/home-assistant/home-assistant:dev
    volumes:
      - /Volumes/Mac/vscode/docker-compose/HAS/:/config
    ports:
      - "8123:8123"
    environment:
      - TZ=Asia/Shanghai
